/**
 * Shared fixture for integration tests. Creates a predictable schema
 * (`test_fixture`) with tables, views, functions, indexes, FKs, and a
 * quoted-name identifier so we can exercise every tool against a real DB.
 *
 * Gated on POSTGRES_MCP_INTEGRATION=1 so `npm test` without a DB stays fast.
 */

import { runInternal, shutdown, withSharedClient } from "../api.js";

export const FIXTURE_SCHEMA = "test_fixture";

// Cluster-scoped role names used by pg_list_roles.member_of regression
// coverage. Roles can't live inside a schema, so they're cleaned up in
// teardownFixtures rather than dropped along with the schema CASCADE.
export const FIXTURE_GROUP_ROLE = "mcp_test_group";
export const FIXTURE_MEMBER_ROLE = "mcp_test_member";

// Limited-privilege login role used by the pg_replication_status _warnings
// partial-failure test. The role has CONNECT only -- no pg_monitor, no
// REPLICATION attribute. On a standalone cluster only ONE of the handler's
// three sub-queries is actually privilege-gated for this role: the
// wal_position fetch, pg_current_wal_lsn(). The slots (pg_replication_slots)
// and replicas (pg_stat_replication) sub-queries return empty rows even to a
// non-pg_monitor role on an instance with no slots / no replicas, so they
// succeed rather than warn. To force a real permission-denied the test also
// REVOKEs PUBLIC EXECUTE on pg_current_wal_lsn(); the role then hits 42501 on
// that one sub-query, and the handler must surface it via the _warnings array
// (rather than the pre-0.6.1 short-circuit return on first failure) while the
// slots/replicas results stay readable. Password is fixed so the test can
// construct the limited DATABASE_URL deterministically.
export const FIXTURE_LIMITED_ROLE = "mcp_test_restricted";
export const FIXTURE_LIMITED_PASSWORD = "restricted_pw";

// Generated / identity column fixture. One table carries all four column
// shapes pg_describe_table has to tell apart: a STORED generated column, a
// GENERATED ALWAYS AS IDENTITY column, a GENERATED BY DEFAULT AS IDENTITY
// column, and an ordinary column with a plain DEFAULT. The plain-DEFAULT
// column is the control for the `default_value` CASE -- that CASE only reports
// a pg_attrdef expression when attgenerated = '', so a regression that
// inverted or widened the test would null out every real default while the
// generated columns still looked correct.
export const FIXTURE_GENERATED_TABLE = "generated_cols";
export const FIXTURE_GENERATED_STORED_COLUMN = "area";
export const FIXTURE_IDENTITY_ALWAYS_COLUMN = "id";
export const FIXTURE_IDENTITY_BY_DEFAULT_COLUMN = "legacy_id";
export const FIXTURE_PLAIN_DEFAULT_COLUMN = "label";

// Wraparound fixture pair for pg_advisor.wraparound_risk. The advisor resolves
// a table's freeze horizon as COALESCE(reloption, GUC), so proving the
// reloption branch fires needs a table whose override is nowhere near the GUC:
// 100000 / 10000 are the per-table minimums postgres accepts, 2000x and 40000x
// below the 200000000 / 400000000 GUC defaults. A reported freeze_max_age of
// 100000 therefore cannot have come from the fallback, and the control table
// pins the other side of the same COALESCE.
//
// That gap is also what makes the ratio testable without controlling the XID
// counter: both tables are created back to back, so age(relfrozenxid) is
// identical to within a few XIDs and the override row's xid_ratio is exactly
// 2000x the control's however many transactions the run has burned. A
// wraparoundThreshold low enough to clear age/100000 but not age/200000000
// surfaces the override row alone; at the 0.5 default neither appears, so the
// pair cannot leak into other advisor assertions.
export const FIXTURE_WRAPAROUND_OVERRIDE_TABLE = "wraparound_override";
export const FIXTURE_WRAPAROUND_CONTROL_TABLE = "wraparound_control";
export const FIXTURE_WRAPAROUND_FREEZE_MAX_AGE = 100_000;
export const FIXTURE_WRAPAROUND_MULTIXACT_FREEZE_MAX_AGE = 10_000;

export function integrationEnabled(): boolean {
  return process.env.POSTGRES_MCP_INTEGRATION === "1";
}

export const FDW_SERVER_NAME = "mcp_test_fdw_server";

/**
 * Best-effort: set up a self-referential postgres_fdw foreign table so the
 * suite can exercise the foreign-table branches of pg_describe_table and
 * pg_advisor. Returns true if the foreign table was created, false if
 * postgres_fdw is unavailable or DATABASE_URL can't be parsed.
 *
 * The SERVER and USER MAPPING are cluster-level objects and must be cleaned
 * up explicitly in teardownFixtures (DROP SCHEMA CASCADE removes the foreign
 * table but not the server).
 */
export async function setupFdwFixture(): Promise<boolean> {
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) return false;

  let url: URL;
  try {
    // URL constructor rejects the postgres:// scheme; swap to http:// for parsing only.
    url = new URL(dbUrl.replace(/^postgres(?:ql)?:\/\//, "http://"));
  } catch {
    return false;
  }

  const host = url.hostname || "localhost";
  const port = url.port || "5432";
  const dbname = url.pathname.slice(1) || "postgres";
  const user = decodeURIComponent(url.username) || "postgres";
  const password = decodeURIComponent(url.password);

  // Single-quote-escape each value so embedded quotes don't break the OPTIONS clause.
  const q = (s: string) => s.replace(/'/g, "''");

  // Omit the password option entirely for trust-auth setups (empty password in
  // DATABASE_URL). Passing password='' to a trust-auth cluster causes some FDW
  // versions to reject the mapping with "authentication failed".
  const userMappingOpts = password
    ? ` OPTIONS (user '${q(user)}', password '${q(password)}')`
    : ` OPTIONS (user '${q(user)}')`;

  const statements = [
    `CREATE EXTENSION IF NOT EXISTS postgres_fdw`,
    `DROP SERVER IF EXISTS ${FDW_SERVER_NAME} CASCADE`,
    `CREATE SERVER ${FDW_SERVER_NAME} FOREIGN DATA WRAPPER postgres_fdw` +
      ` OPTIONS (host '${q(host)}', port '${q(port)}', dbname '${q(dbname)}')`,
    `CREATE USER MAPPING FOR CURRENT_USER SERVER ${FDW_SERVER_NAME}` + userMappingOpts,
    // A foreign table with no defined PK -- exercises pg_describe_table.
    `CREATE FOREIGN TABLE ${FIXTURE_SCHEMA}.remote_users` +
      ` (id integer NOT NULL, email text NOT NULL)` +
      ` SERVER ${FDW_SERVER_NAME}` +
      ` OPTIONS (schema_name '${q(FIXTURE_SCHEMA)}', table_name 'users')`,
  ];

  for (const sql of statements) {
    const res = await runInternal(sql);
    if (!res.ok) {
      console.error(
        `[FDW fixture] statement failed, skipping FDW tests:\n  ${sql.slice(0, 120)}\n  error: ${(res as { error?: string }).error ?? "unknown"}`,
      );
      return false;
    }
  }
  return true;
}

/**
 * Guard for tests that mutate pg_catalog grants (e.g. REVOKE EXECUTE on a
 * built-in function). A hard process kill between REVOKE and GRANT leaves the
 * cluster broken until manually repaired, so these tests only run when the
 * caller explicitly opts in with POSTGRES_MCP_DESTRUCTIVE_TESTS=1 -- meaning
 * the cluster is disposable (CI, ephemeral Docker, etc.).
 */
export function destructiveTestsEnabled(): boolean {
  return process.env.POSTGRES_MCP_DESTRUCTIVE_TESTS === "1";
}

/** Drop + recreate the fixture schema so each test run starts clean. */
export async function setupFixtures(): Promise<void> {
  const statements = [
    `DROP SCHEMA IF EXISTS ${FIXTURE_SCHEMA} CASCADE`,
    `CREATE SCHEMA ${FIXTURE_SCHEMA}`,

    `CREATE TABLE ${FIXTURE_SCHEMA}.users (
       id SERIAL PRIMARY KEY,
       email TEXT NOT NULL UNIQUE,
       created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
       metadata JSONB
     )`,

    `CREATE TABLE ${FIXTURE_SCHEMA}.posts (
       id SERIAL PRIMARY KEY,
       user_id INTEGER NOT NULL REFERENCES ${FIXTURE_SCHEMA}.users(id) ON DELETE CASCADE,
       title TEXT NOT NULL,
       body TEXT
     )`,
    `CREATE INDEX posts_user_id_idx ON ${FIXTURE_SCHEMA}.posts(user_id)`,

    // A quoted/awkward identifier - proves the validateIdent loosening works.
    `CREATE TABLE ${FIXTURE_SCHEMA}."Odd Table" (
       id SERIAL PRIMARY KEY,
       "weird-col" TEXT
     )`,

    `CREATE VIEW ${FIXTURE_SCHEMA}.user_post_counts AS
       SELECT u.id, u.email, COUNT(p.id) AS post_count
       FROM ${FIXTURE_SCHEMA}.users u
       LEFT JOIN ${FIXTURE_SCHEMA}.posts p ON p.user_id = u.id
       GROUP BY u.id, u.email`,

    `CREATE FUNCTION ${FIXTURE_SCHEMA}.user_count() RETURNS BIGINT
       LANGUAGE SQL AS $$ SELECT COUNT(*) FROM ${FIXTURE_SCHEMA}.users $$`,

    // Constraints fixture: CHECK + UNIQUE non-PK so describe_table.constraints
    // has rows to exercise. EXCLUDE needs btree_gist; skip to keep fixture
    // dependency-free.
    `CREATE TABLE ${FIXTURE_SCHEMA}.products (
       id SERIAL PRIMARY KEY,
       sku TEXT NOT NULL,
       price NUMERIC NOT NULL,
       CONSTRAINT products_sku_unique UNIQUE (sku),
       CONSTRAINT products_price_positive CHECK (price > 0)
     )`,

    // Partition fixture: declarative range partitioning so describe_table
    // returns partition_of (on a child) and partitions (on the parent).
    `CREATE TABLE ${FIXTURE_SCHEMA}.events (
       id BIGSERIAL,
       occurred_at DATE NOT NULL,
       payload TEXT,
       PRIMARY KEY (id, occurred_at)
     ) PARTITION BY RANGE (occurred_at)`,
    `CREATE TABLE ${FIXTURE_SCHEMA}.events_2026 PARTITION OF ${FIXTURE_SCHEMA}.events
       FOR VALUES FROM ('2026-01-01') TO ('2027-01-01')`,

    // Advisor fixture: a heap table with no primary key. Used by the
    // pg_advisor tables_without_primary_key check.
    `CREATE TABLE ${FIXTURE_SCHEMA}.no_pk_table (id INT, label TEXT)`,

    // Covering-PK fixture: PRIMARY KEY ... INCLUDE (PG11+). `label` lands in
    // pg_index.indkey alongside the key column but is NOT part of the key --
    // indnkeyatts is 1. pg_describe_table must report primary_key = ["id"]
    // only. Matching on the whole indkey vector reported ["id","label"], which
    // would send an agent to build a wrong ON CONFLICT target.
    `CREATE TABLE ${FIXTURE_SCHEMA}.covering_pk (
       id INT NOT NULL,
       label TEXT,
       note TEXT,
       CONSTRAINT covering_pk_pkey PRIMARY KEY (id) INCLUDE (label)
     )`,

    // Generated / identity fixture: a STORED generated column, both identity
    // flavors, and a plain DEFAULT column in one relation. `area` must report
    // generation_expression and never default_value (reported as a default it
    // reads as "optional" and the agent writes an INSERT postgres rejects);
    // `id` / `legacy_id` must report identity always / by_default; `label` is
    // the control that proves the attgenerated = '' arm of the default_value
    // CASE still surfaces an ordinary default instead of nulling all of them.
    `CREATE TABLE ${FIXTURE_SCHEMA}.${FIXTURE_GENERATED_TABLE} (
       ${FIXTURE_IDENTITY_ALWAYS_COLUMN} INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
       ${FIXTURE_IDENTITY_BY_DEFAULT_COLUMN} INTEGER GENERATED BY DEFAULT AS IDENTITY,
       width NUMERIC NOT NULL,
       height NUMERIC NOT NULL,
       ${FIXTURE_GENERATED_STORED_COLUMN} NUMERIC GENERATED ALWAYS AS (width * height) STORED,
       ${FIXTURE_PLAIN_DEFAULT_COLUMN} TEXT NOT NULL DEFAULT 'unlabeled'
     )`,

    // Advisor fixture: a partitioned table parent with NO primary key.
    // pg_advisor must flag this (relkind='p' coverage). The negative case
    // is covered by `events` above, which is also partitioned but DOES
    // have a PK.
    `CREATE TABLE ${FIXTURE_SCHEMA}.no_pk_partitioned (id INT, occurred_at DATE)
       PARTITION BY RANGE (occurred_at)`,

    // Materialized view fixture: covers the `includeMaterialized` true /
    // false branches of pg_list_views and the relkind='m' bucket of
    // pg_list_tables (when includeViews is true).
    `CREATE MATERIALIZED VIEW ${FIXTURE_SCHEMA}.user_post_counts_mv AS
       SELECT u.id, u.email, COUNT(p.id) AS post_count
       FROM ${FIXTURE_SCHEMA}.users u
       LEFT JOIN ${FIXTURE_SCHEMA}.posts p ON p.user_id = u.id
       GROUP BY u.id, u.email`,

    // Advisor fixture: a sequence advanced to 80% of its max so pg_advisor
    // sequence_exhaustion has a positive case to flag. MAXVALUE 1000 keeps
    // the arithmetic obvious; setval(800) puts it well past the 50% default
    // threshold and tests the numeric-precision formula 0.5.2 introduced.
    `CREATE SEQUENCE ${FIXTURE_SCHEMA}.near_full_seq MAXVALUE 1000`,
    `SELECT setval('${FIXTURE_SCHEMA}.near_full_seq', 800)`,

    // Advisor fixture: wraparound override vs GUC fallback. Created back to
    // back so the only thing separating the two rows in wraparound_risk.tables
    // is the freeze_max_age divisor -- which is exactly the per-table
    // reloption branch under test. Both are plain heap tables with a PK so
    // they stay out of the tables_without_primary_key list. Setting these
    // storage parameters is an owner-level ALTER; no superuser involved.
    `CREATE TABLE ${FIXTURE_SCHEMA}.${FIXTURE_WRAPAROUND_OVERRIDE_TABLE} (id INT PRIMARY KEY, payload TEXT)`,
    `CREATE TABLE ${FIXTURE_SCHEMA}.${FIXTURE_WRAPAROUND_CONTROL_TABLE} (id INT PRIMARY KEY, payload TEXT)`,
    `ALTER TABLE ${FIXTURE_SCHEMA}.${FIXTURE_WRAPAROUND_OVERRIDE_TABLE} SET (
       autovacuum_freeze_max_age = ${FIXTURE_WRAPAROUND_FREEZE_MAX_AGE},
       autovacuum_multixact_freeze_max_age = ${FIXTURE_WRAPAROUND_MULTIXACT_FREEZE_MAX_AGE}
     )`,

    `INSERT INTO ${FIXTURE_SCHEMA}.users (email, metadata) VALUES
       ('a@example.com', '{"role":"admin"}'::jsonb),
       ('b@example.com', '{"role":"user"}'::jsonb),
       ('c@example.com', NULL)`,
    `INSERT INTO ${FIXTURE_SCHEMA}.posts (user_id, title, body) VALUES
       (1, 'hello', 'world'),
       (1, 'second', NULL),
       (2, 'another', 'post body')`,

    // Roles fixture for pg_list_roles.member_of regression test. The 0.3.1
    // fix cast member_of to text[] so node-pg returns a JS string[] instead
    // of the raw postgres text form `{a,b}`. Without an actual membership in
    // the cluster, every member_of is `[]` and the cast is never exercised.
    // Drops are idempotent so reruns stay green even after a prior crash.
    `DROP ROLE IF EXISTS ${FIXTURE_MEMBER_ROLE}`,
    `DROP ROLE IF EXISTS ${FIXTURE_GROUP_ROLE}`,
    `CREATE ROLE ${FIXTURE_GROUP_ROLE} NOLOGIN`,
    `CREATE ROLE ${FIXTURE_MEMBER_ROLE} NOLOGIN`,
    `GRANT ${FIXTURE_GROUP_ROLE} TO ${FIXTURE_MEMBER_ROLE}`,

    // Limited login role for the pg_replication_status _warnings test.
    // CONNECT is granted to PUBLIC by default on every postgres database,
    // so we don't need an explicit GRANT here -- the role can connect but
    // can't read any of the replication-monitoring views/functions because
    // it has no pg_monitor / REPLICATION attribute.
    `DROP ROLE IF EXISTS ${FIXTURE_LIMITED_ROLE}`,
    `CREATE ROLE ${FIXTURE_LIMITED_ROLE} LOGIN PASSWORD '${FIXTURE_LIMITED_PASSWORD}'`,
  ];

  for (const sql of statements) {
    const res = await runInternal(sql);
    if (!res.ok) {
      throw new Error(`Fixture setup failed on statement:\n${sql}\n\nError: ${res.error}`);
    }
  }

  // Best-effort: enable HypoPG so pg_explain hypothetical_indexes tests can
  // exercise the positive path. If the binary isn't installed (e.g. PGDG
  // hasn't packaged it for this PG major yet), the test falls back to
  // exercising the "extension not installed" error path.
  await runInternal(`CREATE EXTENSION IF NOT EXISTS hypopg`);

  // Best-effort: pgstattuple ships in postgresql-contrib and needs no
  // shared_preload_libraries entry, so a plain CREATE EXTENSION is enough.
  // Without it every pg_table_bloat method='approx'/'exact' test takes the
  // "extension not installed" early return and the pgstattuple SQL (the
  // LATERAL join, the approx_tuple_count/tuple_count column swap, the
  // relkind IN ('r','m') guard against partitioned parents) never executes.
  await runInternal(`CREATE EXTENSION IF NOT EXISTS pgstattuple`);

  // Best-effort: pg_stat_statements ALSO requires being listed in
  // shared_preload_libraries and a server restart -- scripts/wsl-pg-setup.sh
  // does that. CREATE EXTENSION alone fails when the library isn't preloaded,
  // and pg_top_queries then has no coverage at all (every one of its tests
  // early-returns on "not installed"). Failure here is not fatal: the tests
  // still pass via that branch, they just prove less.
  await runInternal(`CREATE EXTENSION IF NOT EXISTS pg_stat_statements`);

  // Best-effort: set up a self-referential FDW foreign table so foreign-table
  // branches of pg_describe_table and pg_advisor can be exercised.
  _fdwAvailable = await setupFdwFixture();

  // Best-effort: the PG18-only catalog states. Runs after the always-run array
  // rather than inside it -- that array throws on the first failure, and on
  // PG15 / PG17 every statement in here is a syntax error.
  _pg18 = await setupPg18Fixtures();
}

// Tracks whether the FDW foreign table fixture was successfully created.
// Reset by each setupFixtures() call so parallel-file runs stay independent.
let _fdwAvailable = false;

/** True when the postgres_fdw foreign table fixture is in place. */
export function fdwFixtureAvailable(): boolean {
  return _fdwAvailable;
}

// PG18-only fixture object names. Every one of these lives inside
// FIXTURE_SCHEMA, so teardownFixtures' DROP SCHEMA ... CASCADE reclaims them
// all; only the btree_gist extension escapes, deliberately (see
// setupPg18Fixtures).
export const FIXTURE_PG18_VIRTUAL_TABLE = "pg18_virtual_generated";
export const FIXTURE_PG18_VIRTUAL_COLUMN = "doubled";
export const FIXTURE_PG18_NOT_NULL_TABLE = "pg18_not_null_not_valid";
export const FIXTURE_PG18_NOT_NULL_COLUMN = "maybe_null";
export const FIXTURE_PG18_NOT_NULL_CONSTRAINT = "pg18_maybe_null_nn";
export const FIXTURE_PG18_NOT_ENFORCED_TABLE = "pg18_not_enforced";
export const FIXTURE_PG18_NOT_ENFORCED_CHECK = "pg18_amount_positive";
export const FIXTURE_PG18_NOT_ENFORCED_FK = "pg18_not_enforced_user_fk";
export const FIXTURE_PG18_TEMPORAL_TABLE = "pg18_temporal";
export const FIXTURE_PG18_TEMPORAL_PK = "pg18_temporal_pkey";
export const FIXTURE_PG18_TEMPORAL_PERIOD_COLUMN = "valid_at";

/** Which PG18-only fixture objects actually made it into the cluster. */
type Pg18FixtureState = {
  virtualGenerated: boolean;
  notNullNotValid: boolean;
  notEnforced: boolean;
  temporalKey: boolean;
};

// Tracks which PG18-only objects exist. Replaced as a whole by each
// setupFixtures() call so a run against a different major in the matrix can't
// inherit the previous run's answers.
let _pg18: Pg18FixtureState = {
  virtualGenerated: false,
  notNullNotValid: false,
  notEnforced: false,
  temporalKey: false,
};

/**
 * Run a group of statements, stopping at the first failure. Unlike the
 * always-run array in setupFixtures this never throws: on PG15 / PG17 (both in
 * the matrix -- see scripts/wsl-pg-setup.sh) every group below fails on syntax
 * the server has never heard of, and that is the expected outcome, not a
 * broken fixture. A half-created group leaves the partial table behind rather
 * than rolling it back; the probe reports false either way, and DROP SCHEMA
 * CASCADE reclaims the remnant.
 */
/**
 * Run a best-effort statement group ATOMICALLY: either every statement lands
 * or none does.
 *
 * The atomicity is load-bearing, not tidiness. These groups are shaped as
 * `CREATE TABLE ...` followed by a PG18-only `ALTER TABLE ...`, so running
 * them statement-by-statement on PG15/17 left the TABLE behind after the
 * ALTER failed. The probe correctly returned false, but the orphan relation
 * stayed in the fixture schema and showed up in `pg_list_tables` on every
 * older major -- which broke an exact-match assertion in
 * schemas.integration.test.ts that had nothing to do with PG18.
 *
 * Wrapping in a transaction works because PostgreSQL has transactional DDL:
 * the ROLLBACK unwinds the CREATE as cleanly as it unwinds the ALTER. Note
 * `runInternal` runs each call on a pooled connection, so BEGIN/ROLLBACK must
 * ride the SAME client -- hence withSharedClient rather than bare runInternal.
 */
async function tryStatementGroup(statements: string[]): Promise<boolean> {
  return withSharedClient(async (run) => {
    const begun = await run("BEGIN");
    if (!begun.ok) return false;
    for (const sql of statements) {
      const res = await run(sql);
      if (!res.ok) {
        await run("ROLLBACK");
        return false;
      }
    }
    const committed = await run("COMMIT");
    if (!committed.ok) {
      await run("ROLLBACK");
      return false;
    }
    return true;
  });
}

/**
 * Best-effort: create the catalog states that exist only on PostgreSQL 18.
 * Each one changes what pg_describe_table is allowed to claim about a
 * relation, and none of them can be simulated on an older major:
 *
 *   - VIRTUAL generated column (attgenerated = 'v'), the branch of the
 *     `generated` CASE that 's' coverage alone never reaches.
 *   - NOT VALID not-null constraint (contype 'n', convalidated = false), which
 *     is what makes `not_null_validated` false -- the column still reports
 *     nullable: false while pre-existing NULLs sit in the table.
 *   - NOT ENFORCED CHECK and FK (conenforced = false): a referential guarantee
 *     that enforces nothing. The FK also drives the aggregated FK query, whose
 *     GROUP BY has to carry conenforced.
 *   - Temporal PRIMARY KEY (conperiod = true), an overlap key that otherwise
 *     renders as an ordinary equality key.
 *
 * These cannot join setupFixtures' statements array, which throws on the first
 * failure. Same best-effort shape as the hypopg / pgstattuple /
 * pg_stat_statements extensions above -- attempt it, swallow the failure, and
 * export one probe per object so a dependent test skips on the object it
 * actually needs instead of guessing from the server version.
 */
async function setupPg18Fixtures(): Promise<Pg18FixtureState> {
  const virtualGenerated = await tryStatementGroup([
    `CREATE TABLE ${FIXTURE_SCHEMA}.${FIXTURE_PG18_VIRTUAL_TABLE} (
       id INTEGER PRIMARY KEY,
       base NUMERIC NOT NULL,
       ${FIXTURE_PG18_VIRTUAL_COLUMN} NUMERIC GENERATED ALWAYS AS (base * 2) VIRTUAL
     )`,
  ]);

  const notNullNotValid = await tryStatementGroup([
    `CREATE TABLE ${FIXTURE_SCHEMA}.${FIXTURE_PG18_NOT_NULL_TABLE} (
       id INTEGER PRIMARY KEY,
       ${FIXTURE_PG18_NOT_NULL_COLUMN} TEXT
     )`,
    // The NULL row goes in FIRST, on purpose. ADD ... NOT VALID skips the
    // existing-rows scan, so this row survives the constraint and the table
    // then holds exactly the hazard the tool warns about: a column reporting
    // nullable: false that still contains NULL. Inserting it afterwards would
    // be rejected -- new rows are checked even while the constraint is invalid.
    `INSERT INTO ${FIXTURE_SCHEMA}.${FIXTURE_PG18_NOT_NULL_TABLE} (id, ${FIXTURE_PG18_NOT_NULL_COLUMN}) VALUES (1, NULL)`,
    // PG18's `ADD CONSTRAINT <name> NOT NULL <column> NOT VALID` is the only
    // way to reach convalidated = false on a not-null constraint; ALTER COLUMN
    // ... SET NOT NULL still validates. attnotnull flips to true either way,
    // which is precisely why nullable: false stopped proving anything on 18.
    `ALTER TABLE ${FIXTURE_SCHEMA}.${FIXTURE_PG18_NOT_NULL_TABLE}
       ADD CONSTRAINT ${FIXTURE_PG18_NOT_NULL_CONSTRAINT} NOT NULL ${FIXTURE_PG18_NOT_NULL_COLUMN} NOT VALID`,
  ]);

  // One table carries both NOT ENFORCED shapes: the CHECK lands in the
  // constraints query, the FK in the separate aggregated foreign-keys query.
  // No ON DELETE / ON UPDATE action -- postgres rejects a referential action
  // on a NOT ENFORCED foreign key.
  const notEnforced = await tryStatementGroup([
    `CREATE TABLE ${FIXTURE_SCHEMA}.${FIXTURE_PG18_NOT_ENFORCED_TABLE} (
       id INTEGER PRIMARY KEY,
       user_id INTEGER,
       amount NUMERIC,
       CONSTRAINT ${FIXTURE_PG18_NOT_ENFORCED_CHECK} CHECK (amount > 0) NOT ENFORCED,
       CONSTRAINT ${FIXTURE_PG18_NOT_ENFORCED_FK} FOREIGN KEY (user_id)
         REFERENCES ${FIXTURE_SCHEMA}.users(id) NOT ENFORCED
     )`,
  ]);

  const temporalKey = await tryStatementGroup([
    // The scalar half of a WITHOUT OVERLAPS key is indexed with GiST, and only
    // btree_gist supplies GiST equality for a plain integer (the daterange half
    // is natively GiST). btree_gist is trusted since PG13 and ships in
    // postgresql-contrib, so no superuser is needed -- but if the package is
    // missing this group stops here and the probe reports false. It is created
    // outside FIXTURE_SCHEMA and left installed for the same reason hypopg and
    // pgstattuple are: dropping an extension cascades into anything else in the
    // cluster that came to depend on it.
    `CREATE EXTENSION IF NOT EXISTS btree_gist`,
    `CREATE TABLE ${FIXTURE_SCHEMA}.${FIXTURE_PG18_TEMPORAL_TABLE} (
       id INTEGER NOT NULL,
       ${FIXTURE_PG18_TEMPORAL_PERIOD_COLUMN} daterange NOT NULL,
       note TEXT,
       CONSTRAINT ${FIXTURE_PG18_TEMPORAL_PK}
         PRIMARY KEY (id, ${FIXTURE_PG18_TEMPORAL_PERIOD_COLUMN} WITHOUT OVERLAPS)
     )`,
  ]);

  return { virtualGenerated, notNullNotValid, notEnforced, temporalKey };
}

/** True when the VIRTUAL generated column fixture exists (PG18+ only). */
export function pg18VirtualColumnAvailable(): boolean {
  return _pg18.virtualGenerated;
}

/** True when the NOT NULL NOT VALID constraint fixture exists (PG18+ only). */
export function pg18NotNullNotValidAvailable(): boolean {
  return _pg18.notNullNotValid;
}

/** True when the NOT ENFORCED CHECK + FK fixture exists (PG18+ only). */
export function pg18NotEnforcedAvailable(): boolean {
  return _pg18.notEnforced;
}

/**
 * True when the temporal (WITHOUT OVERLAPS) primary key fixture exists. False
 * on PG18 too when btree_gist could not be installed, which is why this is a
 * separate probe from the other three rather than a shared "is PG18" flag.
 */
export function pg18TemporalKeyAvailable(): boolean {
  return _pg18.temporalKey;
}

/**
 * Second database in the SAME cluster, used to prove pg_top_queries' `dbid`
 * filter actually scopes results. pg_stat_statements is cluster-wide: a query
 * run here lands in the shared view with a different dbid, so it must NOT
 * appear in pg_top_queries results taken against the primary test database.
 *
 * CREATE/DROP DATABASE cannot run inside a transaction block -- runInternal
 * issues on the pool in autocommit, which is why it works here.
 */
export const FIXTURE_OTHER_DB = "postgres_mcp_other";

/**
 * Marker text embedded in the query run against the other database. Distinctive
 * enough that a substring match against pg_stat_statements' normalized query
 * text cannot collide with anything else the suite runs.
 */
export const FIXTURE_OTHER_DB_MARKER = "mcp_dbid_scope_marker_9f3a";

/**
 * Create the second database and run the marker query inside it. Returns false
 * when the database can't be created (insufficient privileges), so the caller
 * can skip rather than fail.
 */
export async function runMarkerQueryInOtherDatabase(): Promise<boolean> {
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) return false;
  // Drop first so a prior crashed run doesn't leave a stale database behind.
  await dropOtherDatabase();
  const created = await runInternal(`CREATE DATABASE ${FIXTURE_OTHER_DB}`);
  if (!created.ok) return false;

  // Connect directly -- the pool is bound to the primary database.
  const { default: pg } = await import("pg");
  const other = new URL(dbUrl.replace(/^postgres(?:ql)?:\/\//, "http://"));
  other.pathname = `/${FIXTURE_OTHER_DB}`;
  const client = new pg.Client({
    connectionString: other.toString().replace(/^http:\/\//, "postgres://"),
  });
  try {
    await client.connect();
    // pg_stat_statements must be enabled per-database to RECORD from it, but
    // the view is cluster-wide, so creating it here is what gets the marker
    // into the shared table. Best-effort: without the preload this fails and
    // the caller's test skips.
    const ext = await client.query(`CREATE EXTENSION IF NOT EXISTS pg_stat_statements`).catch(() => null);
    if (!ext) return false;
    await client.query(`SELECT 1 AS ${FIXTURE_OTHER_DB_MARKER}`);
    return true;
  } catch {
    return false;
  } finally {
    await client.end().catch(() => {});
  }
}

/** Drop the second database. Terminates stragglers so DROP can't be blocked. */
export async function dropOtherDatabase(): Promise<void> {
  await runInternal(
    `SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()`,
    [FIXTURE_OTHER_DB],
  );
  await runInternal(`DROP DATABASE IF EXISTS ${FIXTURE_OTHER_DB}`);
}

/** Clean up the fixture schema, drop cluster-scoped roles, close the pool. */
export async function teardownFixtures(): Promise<void> {
  try {
    await runInternal(`DROP SCHEMA IF EXISTS ${FIXTURE_SCHEMA} CASCADE`);
    // Nothing else to drop for the generated / wraparound / PG18 fixtures:
    // they are all relations inside FIXTURE_SCHEMA, so the CASCADE above takes
    // them. btree_gist stays installed on purpose, like the other best-effort
    // extensions -- DROP EXTENSION would cascade into unrelated cluster objects
    // that came to depend on it.

    // FDW server is a cluster-level object not removed by schema CASCADE.
    await runInternal(`DROP SERVER IF EXISTS ${FDW_SERVER_NAME} CASCADE`);
    // Order matters: drop the member before the group it belongs to so
    // there's no dangling role-membership row.
    await runInternal(`DROP ROLE IF EXISTS ${FIXTURE_MEMBER_ROLE}`);
    await runInternal(`DROP ROLE IF EXISTS ${FIXTURE_GROUP_ROLE}`);
    await runInternal(`DROP ROLE IF EXISTS ${FIXTURE_LIMITED_ROLE}`);
    await dropOtherDatabase();
  } finally {
    await shutdown();
  }
}
